### ISSUE TITLE
aws-list-ec2.py - TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by bartekj** [bartekj/aws-tools#24]
Not sure what exactly is causing the problem but after printing out a larger list of instances it ending like this:
```
Traceback (most recent call last):
  File "/usr/local/bin/aws-list-ec2.py", line 116, in <module>
    main()
  File "/usr/local/bin/aws-list-ec2.py", line 112, in main
    get_ec2()
  File "/usr/local/bin/aws-list-ec2.py", line 100, in get_ec2
    for tag in instance.tags:
TypeError: 'NoneType' object is not iterable
```

**Comment by bartekj** [comment]
Fixed by @uridium at e990ee89fa1df7a09217d9a855ecf3f8b4c54111
