### ISSUE TITLE
AccessKeysPerUser quota

### ISSUE THREAD

**Issue by uridium** [bartekj/aws-tools#29]
If you created more than one Access key ID and want to roll your keys, python throws the exception:

```
Traceback (most recent call last):
  File "/home/radar/.local/bin/aws-roll-keys.py", line 212, in <module>
    main()
  File "/home/radar/.local/bin/aws-roll-keys.py", line 156, in main
    resp = client.create_access_key()
  File "/home/radar/.local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/radar/.local/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.LimitExceededException: An error occurred (LimitExceeded) when calling the CreateAccessKey operation: Cannot exceed quota for AccessKeysPerUser: 2
```

**Comment by bartekj** [comment]
From the log message I can clearly see that the limit for keys is set `AccessKeysPerUser: 2`.
In this case, should be quite normal behaviour. aws-tools will not have a way to create another key. 
I guess it can be handled as an exception :)

**Comment by uridium** [comment]
You're right, there is. But I wanted to handle it catching the exception, instead of printing the whole traceback.

**Comment by uridium** [comment]
Fixed: https://github.com/bartekj/aws-tools/commit/5cb790a6a4604f9a4fbaed4623c8270500fc4e54
