### ISSUE TITLE
Printing detailed view for instances without ARN

### ISSUE THREAD

**Issue by uridium** [bartekj/aws-tools#30]
When using `aws-list-ec2.py -i ID`, some instances return:

```
Traceback (most recent call last):
  File "/home/radar/.local/bin/aws-list-ec2.py", line 123, in <module>
    main()
  File "/home/radar/.local/bin/aws-list-ec2.py", line 119, in main
    get_ec2()
  File "/home/radar/.local/bin/aws-list-ec2.py", line 83, in get_ec2
    ('ARN profile', instance.iam_instance_profile['Arn']),
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by bartekj** [comment]
Are those instances have instance profiles attached?

**Comment by uridium** [comment]
They don't, that's the point :)

**Comment by uridium** [comment]
Fixed: https://github.com/bartekj/aws-tools/commit/f4ca3e6acf49ff49cc8eb6639e8bc24ba09fde3c
